# Generated by Django 5.1.1 on 2024-10-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_users_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='city_or_district',
            field=models.CharField(choices=[('Toshkent shahar', 'Toshkent shahar'), ('Andijon shahar', 'Andijon shahar'), ('Samarqand shahar', 'Samarqand shahar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='region',
            field=models.CharField(choices=[('Toshkent', 'Toshkent'), ('Andijon', 'Andijon'), ('Samarqand', 'Samarqand'), ('Buxoro', 'Buxoro')], max_length=50),
        ),
    ]
